trigger:
  - dev

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
      checkLatest: true
    displayName: 'Install Node.js'

  - script: yarn install
    displayName: yarn install

  - script: yarn test
    displayName: yarn test

  - script: yarn build
    displayName: yarn build

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/build'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      replaceExistingArchive: true
    displayName: archive artifact

  - task: PublishBuildArtifacts@1
    displayName: publich build artifact
    name: drop
